baseURL = "https://www.fuck-contributor-covenant.org"
# canonifyURLs = true
languageCode = "en-us"
title = "Fuck Contributor Covenant"
disableKinds = ["RSS"]

DefaultContentLanguage = "en"
hasCJKLanguage = true
EnableMissingTranslationPlaceholders = true

uglyURLs = true

googleAnalytics = "UA-56802475-1"

[mediaTypes]
[mediaTypes."text/markdown"]
suffix = "md"

[mediaTypes."text/plain"]
suffix = "txt"

[mediaTypes."text/asciidoc"]
suffix = "adoc"

[outputFormats]
[outputFormats.Markdown]
mediaType = "text/markdown"
isPlainText = true
baseName = "CODE_OF_CONDUCT"

[outputFormats.PlainText]
mediaType = "text/plain"
isPlainText = true
baseName = "CODE_OF_CONDUCT"

[outputFormats.AsciiDoc]
mediaType = "text/asciidoc"
isPlainText = true
baseName = "CODE_OF_CONDUCT"

[outputs]
home = ["html"]
page = ["html", "markdown", "plaintext", "asciidoc"]

